@extends('layouts.app.app-frame')

@section('body')
    <p>Hello, world!</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet mattis vulputate enim. Tortor pretium viverra suspendisse potenti nullam ac tortor. Semper auctor neque vitae tempus quam pellentesque nec. Aliquam etiam erat velit scelerisque in. Feugiat in fermentum posuere urna. Vulputate ut pharetra sit amet aliquam id diam maecenas ultricies. In mollis nunc sed id semper risus in hendrerit gravida. Laoreet suspendisse interdum consectetur libero id faucibus. Eget nunc scelerisque viverra mauris.</p>
    <p>Netus et malesuada fames ac turpis egestas. Aliquet bibendum enim facilisis gravida neque convallis. At augue eget arcu dictum varius. Dignissim suspendisse in est ante. Urna porttitor rhoncus dolor purus non enim praesent elementum. Purus semper eget duis at tellus at urna condimentum. Varius morbi enim nunc faucibus a pellentesque sit. Lectus vestibulum mattis ullamcorper velit sed ullamcorper. Massa tincidunt dui ut ornare lectus sit amet est placerat. Venenatis cras sed felis eget. Vitae semper quis lectus nulla at. Tincidunt praesent semper feugiat nibh sed pulvinar proin gravida hendrerit. Euismod nisi porta lorem mollis aliquam ut porttitor leo a. Dui accumsan sit amet nulla facilisi morbi tempus. Pellentesque diam volutpat commodo sed egestas egestas fringilla phasellus faucibus. Adipiscing commodo elit at imperdiet dui accumsan.</p>
    <p>Viverra tellus in hac habitasse platea dictumst. Massa sapien faucibus et molestie. Cursus eget nunc scelerisque viverra. Ipsum dolor sit amet consectetur adipiscing. Felis eget nunc lobortis mattis aliquam. Massa ultricies mi quis hendrerit dolor. Ut morbi tincidunt augue interdum velit euismod in pellentesque massa. Ut etiam sit amet nisl purus in. Amet porttitor eget dolor morbi non arcu. Pulvinar pellentesque habitant morbi tristique senectus et netus et. At elementum eu facilisis sed odio morbi quis. Aliquam malesuada bibendum arcu vitae elementum. Malesuada fames ac turpis egestas sed tempus urna et pharetra. Cursus turpis massa tincidunt dui. Dolor sit amet consectetur adipiscing elit ut aliquam. Tortor dignissim convallis aenean et tortor at risus. Dictum sit amet justo donec enim diam vulputate ut pharetra.</p>
    <p>Leo urna molestie at elementum. Lorem ipsum dolor sit amet consectetur adipiscing elit duis tristique. A pellentesque sit amet porttitor eget dolor. Sed pulvinar proin gravida hendrerit lectus a. Vivamus arcu felis bibendum ut. Pulvinar neque laoreet suspendisse interdum consectetur. Velit ut tortor pretium viverra suspendisse potenti nullam ac. Enim nec dui nunc mattis. Pellentesque habitant morbi tristique senectus et netus et malesuada. Donec ultrices tincidunt arcu non sodales. Sed faucibus turpis in eu mi bibendum neque. Adipiscing elit ut aliquam purus sit amet luctus venenatis lectus. Pretium fusce id velit ut tortor pretium viverra suspendisse. Sed adipiscing diam donec adipiscing tristique. Aliquam ultrices sagittis orci a scelerisque purus semper eget duis. Sed arcu non odio euismod lacinia at quis. Accumsan sit amet nulla facilisi morbi tempus iaculis urna id. Tristique magna sit amet purus gravida quis blandit. Feugiat in fermentum posuere urna nec tincidunt praesent.</p>
    <p>Ultricies mi eget mauris pharetra. Dui ut ornare lectus sit. Imperdiet sed euismod nisi porta lorem mollis aliquam. Malesuada proin libero nunc consequat interdum. Erat velit scelerisque in dictum non consectetur. Diam volutpat commodo sed egestas egestas. Faucibus in ornare quam viverra orci sagittis eu volutpat odio. Quis auctor elit sed vulputate mi sit amet mauris commodo. Tincidunt tortor aliquam nulla facilisi cras. Integer feugiat scelerisque varius morbi enim nunc. Ut aliquam purus sit amet luctus venenatis lectus magna fringilla. A arcu cursus vitae congue mauris rhoncus aenean vel elit.</p>
@endsection



